name: synapse-service-cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up env
        shell: pwsh
        run: |
          $deploymentName = Get-Date -Format "yyyyMMddHHmmss"
          $rgName = "synapse-demo-3"

          echo "DEPLOYMENT_NAME=$deploymentName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "RG_NAME=$rgName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: retrieve env
        shell: pwsh
        run: |
          Write-Host $env:DEPLOYMENT_NAME
          Write-Host $env:RG_NAME
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Service
        shell: pwsh
        run: |
          $deploymentName = $env:DEPLOYMENT_NAME
          $rgName = $env:RG_NAME

          Write-Host $deploymentName 
          Write-Host $rgName 

          $sqlAdminPasswordMap = "synapseSqlAdminPassword=${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}"

          az group create -n $rgName --location eastus
          az deployment group create -g $rgName --template-file ./main.bicep --parameters $sqlAdminPasswordMap --name $deploymentName

      - name: Add access rights
        shell: pwsh
        run: |
          $workspaceName = az deployment group show -g $env:RG_NAME -n $env:DEPLOYMENT_NAME --query properties.outputs.workspaceName.value --output tsv
          Write-Host $workspaceName
          
          # mark garner
          # $IdentityID = "5d9129b8-e338-4a58-9914-fd49a178fc92" 

          # matt lunzer
          $IdentityID = "f4f6643c-87b8-4f6e-81b4-14adac574f70" 

          $deployedIdentityId = az synapse role assignment list --workspace-name azsynapsewksp6d7i --query "[?principalId=='$IdentityID'].principalId" -o tsv
          if ($deployedIdentityID -ne $IdentityID)
          {
            az synapse role assignment create --workspace-name $workspaceName --role "Synapse Administrator" --assignee $IdentityID
          }
