name: synapse-service-cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Service
        shell: pwsh
        run: |
          $deploymentName = Get-Date -Format "yyyyMMddHHmmss"
          $rgName = "synapse-demo"
          $sqlAdminPassword = "synapseSqlAdminPassword=" & ${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}

          $sqlAdminPassword

          az group create -n $rgName --location eastus
          az deployment group create -g $rgNameo --template-file ./main.bicep --parameters $sqlAdminPassword --name $deploymentName

      - name: Add access rights
        shell: pwsh
        run: |
          az synapse role assignment create --workspace-name mynewworkspace-mg --role "Synapse Administrator" --assignee mgarner@microsoft.com