name: synapse-service-cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up env
        shell: pwsh
        run: |
          echo "MY_VARIABLE=hello" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "deploymentName=foo" >> $GITHUB_ENV
          echo "rgName=bar" >> $GITHUB_ENV
    
          Write-Host $env:deploymentName
          Write-Host $env:rgName

          $env:deploymentName = Get-Date -Format "yyyyMMddHHmmss"
          $env:rgName = "synapse-demo"

          Write-Host $env:deploymentName
          Write-Host $env:rgName

      - name: retrieve env
        shell: pwsh
        run: |
          Write-Host $env:MY_VARIABLE
          Write-Host $env:rgName
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Service
        shell: pwsh
        run: |
          $deploymentName = ${{ env.DEPLOYMENT_NAME }}
          $rgName = ${{ env.RG_NAME }}

          Write-Host $deploymentName 
          Write-Host $rgName 

          $sqlAdminPasswordMap = "synapseSqlAdminPassword=${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}"

          az group create -n $rgName --location eastus
          az deployment group create -g $rgName --template-file ./main.bicep --parameters $sqlAdminPasswordMap --name $deploymentName

      - name: Add access rights
        shell: pwsh
        run: |
          Write-Host "Hello"
          az deployment group show \
            -g <resource-group-name> \
            -n <deployment-name> \
            --query properties.outputs.resourceID.value
          //az synapse role assignment create --workspace-name mynewworkspace-mg --role "Synapse Administrator" --assignee tisulliv@microsoft.com