name: synapse-service-cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: set up env
        shell: pwsh
        run: |
          $deploymentName = Get-Date -Format "yyyyMMddHHmmss"
          echo ($deploymentName) >> $env:DEPLOYMENT_NAME

          $rgName = "synapse-demo"
          echo ($rgName) >> $env:RG_NAME
          
      - name: retrieve up env
        shell: pwsh
        run: |
          echo $env:CURRENT_BRANCH
          echo "${{ env.CURRENT_BRANCH }}""
          echo $env:DEPLOYMENT_NAME

          echo $env:RG_NAME
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Service
        shell: pwsh
        run: |
          $deploymentName = ${{ env.DEPLOYMENT_NAME }}
          $rgName = ${{ env.RG_NAME }}

          Write-Host $deploymentName 
          Write-Host $rgName 

          $sqlAdminPasswordMap = "synapseSqlAdminPassword=${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}"

          az group create -n $rgName --location eastus
          az deployment group create -g $rgName --template-file ./main.bicep --parameters $sqlAdminPasswordMap --name $deploymentName

      - name: Add access rights
        shell: pwsh
        run: |
          Write-Host "Hello"
          az deployment group show \
            -g <resource-group-name> \
            -n <deployment-name> \
            --query properties.outputs.resourceID.value
          //az synapse role assignment create --workspace-name mynewworkspace-mg --role "Synapse Administrator" --assignee tisulliv@microsoft.com